// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/mymikasa/pivot/app/user/grpc"
	"github.com/mymikasa/pivot/app/user/ioc"
	"github.com/mymikasa/pivot/app/user/repository"
	"github.com/mymikasa/pivot/app/user/repository/dao"
	"github.com/mymikasa/pivot/app/user/service"
)

// Injectors from wire.go:

func initApp() (*ioc.App, func(), error) {
	config, err := ioc.InitConfig()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := ioc.InitDB(config)
	if err != nil {
		return nil, nil, err
	}
	userDAO := dao.NewUserDAO(db)
	userRepository := repository.NewUserRepository(userDAO)
	issuer := ioc.InitJWTIssuer(config)
	verifier := ioc.InitJWTVerifier(config)
	logger := ioc.InitLogger(config)
	userService := service.NewUserService(userRepository, issuer, verifier, logger)
	userServer := grpc.NewUserServer(userService)
	server := ioc.InitGRPCServer(userServer, verifier)
	httpServer, err := ioc.InitHTTPGateway(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := ioc.NewApp(server, httpServer, logger, config)
	return app, func() {
		cleanup()
	}, nil
}
