// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/mymikasa/pivot/app/kb/grpc"
	"github.com/mymikasa/pivot/app/kb/ioc"
	"github.com/mymikasa/pivot/app/kb/repository"
	"github.com/mymikasa/pivot/app/kb/repository/dao"
	"github.com/mymikasa/pivot/app/kb/service"
)

// Injectors from wire.go:

func initApp() (*ioc.App, func(), error) {
	config, err := ioc.InitConfig()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := ioc.InitDB(config)
	if err != nil {
		return nil, nil, err
	}
	kbDAO := dao.NewKbDAO(db)
	kbRepository := repository.NewKbRepository(kbDAO)
	minIO, err := ioc.InitMinIO(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	logger := ioc.InitLogger(config)
	kbService := service.NewKbService(kbRepository, minIO, logger)
	kbServer := grpc.NewKbServer(kbService)
	verifier := ioc.InitJWTVerifier(config)
	server := ioc.InitGRPCServer(kbServer, verifier)
	httpServer, err := ioc.InitHTTPGateway(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := ioc.NewApp(server, httpServer, logger, config)
	return app, func() {
		cleanup()
	}, nil
}
