// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelParseTaskApiV1ParseTasksTaskIdDeleteData, CancelParseTaskApiV1ParseTasksTaskIdDeleteErrors, CancelParseTaskApiV1ParseTasksTaskIdDeleteResponses, CreateParseTaskApiV1ParseTasksPostData, CreateParseTaskApiV1ParseTasksPostErrors, CreateParseTaskApiV1ParseTasksPostResponses, GetParseTaskApiV1ParseTasksTaskIdGetData, GetParseTaskApiV1ParseTasksTaskIdGetErrors, GetParseTaskApiV1ParseTasksTaskIdGetResponses, ListParseTasksApiV1ParseTasksGetData, ListParseTasksApiV1ParseTasksGetErrors, ListParseTasksApiV1ParseTasksGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Parse Tasks
 */
export const listParseTasksApiV1ParseTasksGet = <ThrowOnError extends boolean = false>(options?: Options<ListParseTasksApiV1ParseTasksGetData, ThrowOnError>) => (options?.client ?? client).get<ListParseTasksApiV1ParseTasksGetResponses, ListParseTasksApiV1ParseTasksGetErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/parse/tasks',
    ...options
});

/**
 * Create Parse Task
 */
export const createParseTaskApiV1ParseTasksPost = <ThrowOnError extends boolean = false>(options: Options<CreateParseTaskApiV1ParseTasksPostData, ThrowOnError>) => (options.client ?? client).post<CreateParseTaskApiV1ParseTasksPostResponses, CreateParseTaskApiV1ParseTasksPostErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/parse/tasks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Cancel Parse Task
 */
export const cancelParseTaskApiV1ParseTasksTaskIdDelete = <ThrowOnError extends boolean = false>(options: Options<CancelParseTaskApiV1ParseTasksTaskIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<CancelParseTaskApiV1ParseTasksTaskIdDeleteResponses, CancelParseTaskApiV1ParseTasksTaskIdDeleteErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/parse/tasks/{task_id}',
    ...options
});

/**
 * Get Parse Task
 */
export const getParseTaskApiV1ParseTasksTaskIdGet = <ThrowOnError extends boolean = false>(options: Options<GetParseTaskApiV1ParseTasksTaskIdGetData, ThrowOnError>) => (options.client ?? client).get<GetParseTaskApiV1ParseTasksTaskIdGetResponses, GetParseTaskApiV1ParseTasksTaskIdGetErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/parse/tasks/{task_id}',
    ...options
});
