// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * CreateParseTaskRequest
 */
export type CreateParseTaskRequest = {
    /**
     * Kb Id
     */
    kb_id: number;
    /**
     * Document Id
     */
    document_id: number;
    /**
     * Object Key
     */
    object_key: string;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Filename
     */
    filename?: string;
    /**
     * User Id
     */
    user_id?: number;
};

/**
 * CreateParseTaskResponse
 */
export type CreateParseTaskResponse = {
    /**
     * Task Id
     */
    task_id: number;
    /**
     * Status
     */
    status: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ListParseTasksResponse
 */
export type ListParseTasksResponse = {
    /**
     * Tasks
     */
    tasks: Array<ParseTaskResponse>;
};

/**
 * ParseTaskResponse
 */
export type ParseTaskResponse = {
    /**
     * Task Id
     */
    task_id: number;
    /**
     * Kb Id
     */
    kb_id: number;
    /**
     * Document Id
     */
    document_id: number;
    /**
     * Status
     */
    status: string;
    /**
     * Progress
     */
    progress: number;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListParseTasksApiV1ParseTasksGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Kb Id
         */
        kb_id?: number | null;
        /**
         * Document Id
         */
        document_id?: number | null;
    };
    url: '/api/v1/parse/tasks';
};

export type ListParseTasksApiV1ParseTasksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListParseTasksApiV1ParseTasksGetError = ListParseTasksApiV1ParseTasksGetErrors[keyof ListParseTasksApiV1ParseTasksGetErrors];

export type ListParseTasksApiV1ParseTasksGetResponses = {
    /**
     * Successful Response
     */
    200: ListParseTasksResponse;
};

export type ListParseTasksApiV1ParseTasksGetResponse = ListParseTasksApiV1ParseTasksGetResponses[keyof ListParseTasksApiV1ParseTasksGetResponses];

export type CreateParseTaskApiV1ParseTasksPostData = {
    body: CreateParseTaskRequest;
    path?: never;
    query?: never;
    url: '/api/v1/parse/tasks';
};

export type CreateParseTaskApiV1ParseTasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateParseTaskApiV1ParseTasksPostError = CreateParseTaskApiV1ParseTasksPostErrors[keyof CreateParseTaskApiV1ParseTasksPostErrors];

export type CreateParseTaskApiV1ParseTasksPostResponses = {
    /**
     * Successful Response
     */
    200: CreateParseTaskResponse;
};

export type CreateParseTaskApiV1ParseTasksPostResponse = CreateParseTaskApiV1ParseTasksPostResponses[keyof CreateParseTaskApiV1ParseTasksPostResponses];

export type CancelParseTaskApiV1ParseTasksTaskIdDeleteData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/v1/parse/tasks/{task_id}';
};

export type CancelParseTaskApiV1ParseTasksTaskIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelParseTaskApiV1ParseTasksTaskIdDeleteError = CancelParseTaskApiV1ParseTasksTaskIdDeleteErrors[keyof CancelParseTaskApiV1ParseTasksTaskIdDeleteErrors];

export type CancelParseTaskApiV1ParseTasksTaskIdDeleteResponses = {
    /**
     * Response Cancel Parse Task Api V1 Parse Tasks  Task Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type CancelParseTaskApiV1ParseTasksTaskIdDeleteResponse = CancelParseTaskApiV1ParseTasksTaskIdDeleteResponses[keyof CancelParseTaskApiV1ParseTasksTaskIdDeleteResponses];

export type GetParseTaskApiV1ParseTasksTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/v1/parse/tasks/{task_id}';
};

export type GetParseTaskApiV1ParseTasksTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetParseTaskApiV1ParseTasksTaskIdGetError = GetParseTaskApiV1ParseTasksTaskIdGetErrors[keyof GetParseTaskApiV1ParseTasksTaskIdGetErrors];

export type GetParseTaskApiV1ParseTasksTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: ParseTaskResponse;
};

export type GetParseTaskApiV1ParseTasksTaskIdGetResponse = GetParseTaskApiV1ParseTasksTaskIdGetResponses[keyof GetParseTaskApiV1ParseTasksTaskIdGetResponses];
