// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type KnowledgeBaseServiceConfirmDocumentUploadBody = {
    objectKey?: string;
    filename?: string;
    contentType?: string;
    fileSize?: string;
};

export type KnowledgeBaseServicePrepareDocumentUploadBody = {
    filename?: string;
    contentType?: string;
    fileSize?: string;
};

export type KnowledgeBaseServiceUpdateKnowledgeBaseBody = {
    name?: string;
    description?: string;
};

export type KnowledgeBaseServiceUploadDocumentSimpleBody = {
    filename?: string;
    contentType?: string;
    data?: string;
};

export type ProtobufAny = {
    '@type'?: string;
    [key: string]: unknown;
};

export type RpcStatus = {
    code?: number;
    message?: string;
    details?: Array<ProtobufAny>;
};

export type V1Chunk = {
    id?: string;
    kbId?: string;
    documentId?: string;
    chunkIndex?: number;
    content?: string;
    tokenCount?: number;
    sourcePage?: number;
    sectionTitle?: string;
    sectionPath?: string;
    filename?: string;
    contentType?: string;
    chunkSize?: number;
    chunkOverlap?: number;
    version?: number;
    userId?: string;
    milvusId?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type V1ConfirmDocumentUploadResponse = {
    document?: V1Document;
};

export type V1CreateKnowledgeBaseRequest = {
    name?: string;
    description?: string;
};

export type V1CreateKnowledgeBaseResponse = {
    kb?: V1KnowledgeBase;
};

export type V1DeleteChunkResponse = {
    [key: string]: unknown;
};

export type V1DeleteDocumentResponse = {
    [key: string]: unknown;
};

export type V1DeleteKnowledgeBaseResponse = {
    [key: string]: unknown;
};

export type V1Document = {
    id?: string;
    kbId?: string;
    filename?: string;
    contentType?: string;
    fileSize?: number;
    status?: string;
    createdAt?: string;
    parseStatus?: string;
    parseTaskId?: string;
    parseProgress?: number;
    parseError?: string;
    parsedAt?: string;
    objectKey?: string;
};

export type V1DownloadDocumentSimpleResponse = {
    filename?: string;
    contentType?: string;
    data?: string;
};

export type V1GetAllUserResponse = {
    users?: Array<V1User>;
};

export type V1GetCurrentUserResponse = {
    user?: V1User;
};

export type V1GetDocumentDownloadUrlResponse = {
    downloadUrl?: string;
    filename?: string;
    contentType?: string;
};

export type V1GetKnowledgeBaseResponse = {
    kb?: V1KnowledgeBase;
};

export type V1GetParseStatusResponse = {
    status?: string;
    progress?: number;
    error?: string;
    parsedAt?: string;
};

export type V1KnowledgeBase = {
    id?: string;
    name?: string;
    description?: string;
    ownerId?: string;
    documentCount?: number;
    createdAt?: string;
    updatedAt?: string;
};

export type V1ListChunksResponse = {
    items?: Array<V1Chunk>;
};

export type V1ListDocumentsResponse = {
    items?: Array<V1Document>;
};

export type V1ListKnowledgeBasesResponse = {
    items?: Array<V1KnowledgeBase>;
};

export type V1LoginRequest = {
    username?: string;
    password?: string;
};

export type V1LoginResponse = {
    accessToken?: string;
    refreshToken?: string;
    tokenType?: string;
    user?: V1User;
};

export type V1LogoutRequest = {
    [key: string]: unknown;
};

export type V1LogoutResponse = {
    [key: string]: unknown;
};

export type V1PrepareDocumentUploadResponse = {
    objectKey?: string;
    uploadUrl?: string;
};

export type V1RefreshTokenRequest = {
    refreshToken?: string;
};

export type V1RefreshTokenResponse = {
    accessToken?: string;
};

export type V1RegisterRequest = {
    username?: string;
    email?: string;
    password?: string;
};

export type V1RegisterResponse = {
    message?: string;
};

export type V1UpdateKnowledgeBaseResponse = {
    kb?: V1KnowledgeBase;
};

export type V1UploadDocumentResponse = {
    document?: V1Document;
};

export type V1User = {
    id?: string;
    username?: string;
    email?: string;
    isActive?: boolean;
    createdAt?: string;
    role?: string;
};

export type KnowledgeBaseServiceListKnowledgeBasesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/kb';
};

export type KnowledgeBaseServiceListKnowledgeBasesErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServiceListKnowledgeBasesError = KnowledgeBaseServiceListKnowledgeBasesErrors[keyof KnowledgeBaseServiceListKnowledgeBasesErrors];

export type KnowledgeBaseServiceListKnowledgeBasesResponses = {
    /**
     * A successful response.
     */
    200: V1ListKnowledgeBasesResponse;
};

export type KnowledgeBaseServiceListKnowledgeBasesResponse = KnowledgeBaseServiceListKnowledgeBasesResponses[keyof KnowledgeBaseServiceListKnowledgeBasesResponses];

export type KnowledgeBaseServiceCreateKnowledgeBaseData = {
    body: V1CreateKnowledgeBaseRequest;
    path?: never;
    query?: never;
    url: '/api/v1/kb';
};

export type KnowledgeBaseServiceCreateKnowledgeBaseErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServiceCreateKnowledgeBaseError = KnowledgeBaseServiceCreateKnowledgeBaseErrors[keyof KnowledgeBaseServiceCreateKnowledgeBaseErrors];

export type KnowledgeBaseServiceCreateKnowledgeBaseResponses = {
    /**
     * A successful response.
     */
    200: V1CreateKnowledgeBaseResponse;
};

export type KnowledgeBaseServiceCreateKnowledgeBaseResponse = KnowledgeBaseServiceCreateKnowledgeBaseResponses[keyof KnowledgeBaseServiceCreateKnowledgeBaseResponses];

export type KnowledgeBaseServiceGetKnowledgeBaseData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/kb/{id}';
};

export type KnowledgeBaseServiceGetKnowledgeBaseErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServiceGetKnowledgeBaseError = KnowledgeBaseServiceGetKnowledgeBaseErrors[keyof KnowledgeBaseServiceGetKnowledgeBaseErrors];

export type KnowledgeBaseServiceGetKnowledgeBaseResponses = {
    /**
     * A successful response.
     */
    200: V1GetKnowledgeBaseResponse;
};

export type KnowledgeBaseServiceGetKnowledgeBaseResponse = KnowledgeBaseServiceGetKnowledgeBaseResponses[keyof KnowledgeBaseServiceGetKnowledgeBaseResponses];

export type KnowledgeBaseServiceDeleteKnowledgeBaseData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/kb/{id}/delete';
};

export type KnowledgeBaseServiceDeleteKnowledgeBaseErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServiceDeleteKnowledgeBaseError = KnowledgeBaseServiceDeleteKnowledgeBaseErrors[keyof KnowledgeBaseServiceDeleteKnowledgeBaseErrors];

export type KnowledgeBaseServiceDeleteKnowledgeBaseResponses = {
    /**
     * A successful response.
     */
    200: V1DeleteKnowledgeBaseResponse;
};

export type KnowledgeBaseServiceDeleteKnowledgeBaseResponse = KnowledgeBaseServiceDeleteKnowledgeBaseResponses[keyof KnowledgeBaseServiceDeleteKnowledgeBaseResponses];

export type KnowledgeBaseServiceUpdateKnowledgeBaseData = {
    body: KnowledgeBaseServiceUpdateKnowledgeBaseBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/kb/{id}/update';
};

export type KnowledgeBaseServiceUpdateKnowledgeBaseErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServiceUpdateKnowledgeBaseError = KnowledgeBaseServiceUpdateKnowledgeBaseErrors[keyof KnowledgeBaseServiceUpdateKnowledgeBaseErrors];

export type KnowledgeBaseServiceUpdateKnowledgeBaseResponses = {
    /**
     * A successful response.
     */
    200: V1UpdateKnowledgeBaseResponse;
};

export type KnowledgeBaseServiceUpdateKnowledgeBaseResponse = KnowledgeBaseServiceUpdateKnowledgeBaseResponses[keyof KnowledgeBaseServiceUpdateKnowledgeBaseResponses];

export type KnowledgeBaseServiceListDocumentsData = {
    body?: never;
    path: {
        kbId: string;
    };
    query?: never;
    url: '/api/v1/kb/{kbId}/documents';
};

export type KnowledgeBaseServiceListDocumentsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServiceListDocumentsError = KnowledgeBaseServiceListDocumentsErrors[keyof KnowledgeBaseServiceListDocumentsErrors];

export type KnowledgeBaseServiceListDocumentsResponses = {
    /**
     * A successful response.
     */
    200: V1ListDocumentsResponse;
};

export type KnowledgeBaseServiceListDocumentsResponse = KnowledgeBaseServiceListDocumentsResponses[keyof KnowledgeBaseServiceListDocumentsResponses];

export type KnowledgeBaseServiceConfirmDocumentUploadData = {
    body: KnowledgeBaseServiceConfirmDocumentUploadBody;
    path: {
        kbId: string;
    };
    query?: never;
    url: '/api/v1/kb/{kbId}/documents/confirm-upload';
};

export type KnowledgeBaseServiceConfirmDocumentUploadErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServiceConfirmDocumentUploadError = KnowledgeBaseServiceConfirmDocumentUploadErrors[keyof KnowledgeBaseServiceConfirmDocumentUploadErrors];

export type KnowledgeBaseServiceConfirmDocumentUploadResponses = {
    /**
     * A successful response.
     */
    200: V1ConfirmDocumentUploadResponse;
};

export type KnowledgeBaseServiceConfirmDocumentUploadResponse = KnowledgeBaseServiceConfirmDocumentUploadResponses[keyof KnowledgeBaseServiceConfirmDocumentUploadResponses];

export type KnowledgeBaseServicePrepareDocumentUploadData = {
    body: KnowledgeBaseServicePrepareDocumentUploadBody;
    path: {
        kbId: string;
    };
    query?: never;
    url: '/api/v1/kb/{kbId}/documents/prepare-upload';
};

export type KnowledgeBaseServicePrepareDocumentUploadErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServicePrepareDocumentUploadError = KnowledgeBaseServicePrepareDocumentUploadErrors[keyof KnowledgeBaseServicePrepareDocumentUploadErrors];

export type KnowledgeBaseServicePrepareDocumentUploadResponses = {
    /**
     * A successful response.
     */
    200: V1PrepareDocumentUploadResponse;
};

export type KnowledgeBaseServicePrepareDocumentUploadResponse = KnowledgeBaseServicePrepareDocumentUploadResponses[keyof KnowledgeBaseServicePrepareDocumentUploadResponses];

export type KnowledgeBaseServiceUploadDocumentSimpleData = {
    body: KnowledgeBaseServiceUploadDocumentSimpleBody;
    path: {
        kbId: string;
    };
    query?: never;
    url: '/api/v1/kb/{kbId}/documents/upload';
};

export type KnowledgeBaseServiceUploadDocumentSimpleErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServiceUploadDocumentSimpleError = KnowledgeBaseServiceUploadDocumentSimpleErrors[keyof KnowledgeBaseServiceUploadDocumentSimpleErrors];

export type KnowledgeBaseServiceUploadDocumentSimpleResponses = {
    /**
     * A successful response.
     */
    200: V1UploadDocumentResponse;
};

export type KnowledgeBaseServiceUploadDocumentSimpleResponse = KnowledgeBaseServiceUploadDocumentSimpleResponses[keyof KnowledgeBaseServiceUploadDocumentSimpleResponses];

export type KnowledgeBaseServiceListChunksData = {
    body?: never;
    path: {
        kbId: string;
        docId: string;
    };
    query?: never;
    url: '/api/v1/kb/{kbId}/documents/{docId}/chunks';
};

export type KnowledgeBaseServiceListChunksErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServiceListChunksError = KnowledgeBaseServiceListChunksErrors[keyof KnowledgeBaseServiceListChunksErrors];

export type KnowledgeBaseServiceListChunksResponses = {
    /**
     * A successful response.
     */
    200: V1ListChunksResponse;
};

export type KnowledgeBaseServiceListChunksResponse = KnowledgeBaseServiceListChunksResponses[keyof KnowledgeBaseServiceListChunksResponses];

export type KnowledgeBaseServiceDeleteChunkData = {
    body?: never;
    path: {
        kbId: string;
        docId: string;
        chunkIndex: number;
    };
    query?: never;
    url: '/api/v1/kb/{kbId}/documents/{docId}/chunks/{chunkIndex}/delete';
};

export type KnowledgeBaseServiceDeleteChunkErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServiceDeleteChunkError = KnowledgeBaseServiceDeleteChunkErrors[keyof KnowledgeBaseServiceDeleteChunkErrors];

export type KnowledgeBaseServiceDeleteChunkResponses = {
    /**
     * A successful response.
     */
    200: V1DeleteChunkResponse;
};

export type KnowledgeBaseServiceDeleteChunkResponse = KnowledgeBaseServiceDeleteChunkResponses[keyof KnowledgeBaseServiceDeleteChunkResponses];

export type KnowledgeBaseServiceDeleteDocumentData = {
    body?: never;
    path: {
        kbId: string;
        docId: string;
    };
    query?: never;
    url: '/api/v1/kb/{kbId}/documents/{docId}/delete';
};

export type KnowledgeBaseServiceDeleteDocumentErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServiceDeleteDocumentError = KnowledgeBaseServiceDeleteDocumentErrors[keyof KnowledgeBaseServiceDeleteDocumentErrors];

export type KnowledgeBaseServiceDeleteDocumentResponses = {
    /**
     * A successful response.
     */
    200: V1DeleteDocumentResponse;
};

export type KnowledgeBaseServiceDeleteDocumentResponse = KnowledgeBaseServiceDeleteDocumentResponses[keyof KnowledgeBaseServiceDeleteDocumentResponses];

export type KnowledgeBaseServiceDownloadDocumentSimpleData = {
    body?: never;
    path: {
        kbId: string;
        docId: string;
    };
    query?: never;
    url: '/api/v1/kb/{kbId}/documents/{docId}/download';
};

export type KnowledgeBaseServiceDownloadDocumentSimpleErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServiceDownloadDocumentSimpleError = KnowledgeBaseServiceDownloadDocumentSimpleErrors[keyof KnowledgeBaseServiceDownloadDocumentSimpleErrors];

export type KnowledgeBaseServiceDownloadDocumentSimpleResponses = {
    /**
     * A successful response.
     */
    200: V1DownloadDocumentSimpleResponse;
};

export type KnowledgeBaseServiceDownloadDocumentSimpleResponse = KnowledgeBaseServiceDownloadDocumentSimpleResponses[keyof KnowledgeBaseServiceDownloadDocumentSimpleResponses];

export type KnowledgeBaseServiceGetDocumentDownloadUrlData = {
    body?: never;
    path: {
        kbId: string;
        docId: string;
    };
    query?: never;
    url: '/api/v1/kb/{kbId}/documents/{docId}/download-url';
};

export type KnowledgeBaseServiceGetDocumentDownloadUrlErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServiceGetDocumentDownloadUrlError = KnowledgeBaseServiceGetDocumentDownloadUrlErrors[keyof KnowledgeBaseServiceGetDocumentDownloadUrlErrors];

export type KnowledgeBaseServiceGetDocumentDownloadUrlResponses = {
    /**
     * A successful response.
     */
    200: V1GetDocumentDownloadUrlResponse;
};

export type KnowledgeBaseServiceGetDocumentDownloadUrlResponse = KnowledgeBaseServiceGetDocumentDownloadUrlResponses[keyof KnowledgeBaseServiceGetDocumentDownloadUrlResponses];

export type KnowledgeBaseServiceGetParseStatusData = {
    body?: never;
    path: {
        kbId: string;
        docId: string;
    };
    query?: never;
    url: '/api/v1/kb/{kbId}/documents/{docId}/parse-status';
};

export type KnowledgeBaseServiceGetParseStatusErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type KnowledgeBaseServiceGetParseStatusError = KnowledgeBaseServiceGetParseStatusErrors[keyof KnowledgeBaseServiceGetParseStatusErrors];

export type KnowledgeBaseServiceGetParseStatusResponses = {
    /**
     * A successful response.
     */
    200: V1GetParseStatusResponse;
};

export type KnowledgeBaseServiceGetParseStatusResponse = KnowledgeBaseServiceGetParseStatusResponses[keyof KnowledgeBaseServiceGetParseStatusResponses];

export type UserServiceGetAllUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type UserServiceGetAllUserErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceGetAllUserError = UserServiceGetAllUserErrors[keyof UserServiceGetAllUserErrors];

export type UserServiceGetAllUserResponses = {
    /**
     * A successful response.
     */
    200: V1GetAllUserResponse;
};

export type UserServiceGetAllUserResponse = UserServiceGetAllUserResponses[keyof UserServiceGetAllUserResponses];

export type UserServiceLoginData = {
    body: V1LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/login';
};

export type UserServiceLoginErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceLoginError = UserServiceLoginErrors[keyof UserServiceLoginErrors];

export type UserServiceLoginResponses = {
    /**
     * A successful response.
     */
    200: V1LoginResponse;
};

export type UserServiceLoginResponse = UserServiceLoginResponses[keyof UserServiceLoginResponses];

export type UserServiceLogoutData = {
    body: V1LogoutRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/logout';
};

export type UserServiceLogoutErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceLogoutError = UserServiceLogoutErrors[keyof UserServiceLogoutErrors];

export type UserServiceLogoutResponses = {
    /**
     * A successful response.
     */
    200: V1LogoutResponse;
};

export type UserServiceLogoutResponse = UserServiceLogoutResponses[keyof UserServiceLogoutResponses];

export type UserServiceGetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UserServiceGetCurrentUserErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceGetCurrentUserError = UserServiceGetCurrentUserErrors[keyof UserServiceGetCurrentUserErrors];

export type UserServiceGetCurrentUserResponses = {
    /**
     * A successful response.
     */
    200: V1GetCurrentUserResponse;
};

export type UserServiceGetCurrentUserResponse = UserServiceGetCurrentUserResponses[keyof UserServiceGetCurrentUserResponses];

export type UserServiceRefreshTokenData = {
    body: V1RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/refresh';
};

export type UserServiceRefreshTokenErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceRefreshTokenError = UserServiceRefreshTokenErrors[keyof UserServiceRefreshTokenErrors];

export type UserServiceRefreshTokenResponses = {
    /**
     * A successful response.
     */
    200: V1RefreshTokenResponse;
};

export type UserServiceRefreshTokenResponse = UserServiceRefreshTokenResponses[keyof UserServiceRefreshTokenResponses];

export type UserServiceRegisterData = {
    body: V1RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/register';
};

export type UserServiceRegisterErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceRegisterError = UserServiceRegisterErrors[keyof UserServiceRegisterErrors];

export type UserServiceRegisterResponses = {
    /**
     * A successful response.
     */
    200: V1RegisterResponse;
};

export type UserServiceRegisterResponse = UserServiceRegisterResponses[keyof UserServiceRegisterResponses];
